global:
  application:
    cluster:
      name: "in-cluster"
      server: "https://kubernetes.default.svc"
    project: default

keda:
  enabled: false
  namespace: keda
  values: { }

nginx:
  enabled: false
  namespace: nginx-ingress
  values: { }


sealedSecrets:
  enabled: false
  namespace: kube-system
  values: { }

postgresql:
  enabled: false
  namespace: postgresql
  values:
    global:
      postgresql:
        auth:
          postgresPassword: "test"
          username: "test"


certManager:
  enabled: false
  namespace: cert-manager
  values:
    installCRDs: true

