{{- if .Values.secret.enabled -}}

apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ include "django.fullname" . }}-secret
spec:
  path: {{ include "django.fullname" . }}/{{ .Values.environment }}
  type: Opaque

{{- end }}
