apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name .Values.celery.flower.componentName }}
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
      {{- include "django.labels" . | nindent 4 }}
spec:
  type: {{ .Values.celery.flower.service.type }}
  {{- with .Values.celery.flower.service.port }}
  ports:
    - port: {{ .number }}
      targetPort: {{ .name }}
      protocol: TCP
      name: {{ .name }}
  {{- end }}
  selector:
    app.kubernetes.io/component: {{ .Values.celery.flower.componentName }}
